import React, { useState, useEffect } from 'react';
import { PageHeader } from '../components/PageHeader';
import { IncidentCard } from '../components/IncidentCard';
import { StatusBadge } from '../components/StatusBadge';
import { incidentsApi } from '../services/api';
import { Incident, IncidentStatus } from '../types';
import { AlertOctagon, Filter, RefreshCw, Shield } from 'lucide-react';
import { Link } from 'react-router-dom';

export const IncidentCenter: React.FC = () => {
  const [incidents, setIncidents] = useState<Incident[]>([]);
  const [selectedIncident, setSelectedIncident] = useState<Incident | null>(null);
  const [selectedSeverity, setSelectedSeverity] = useState<string>('ALL');
  const [selectedStatus, setSelectedStatus] = useState<string>('ALL');
  const [loading, setLoading] = useState(true);
  const [updating, setUpdating] = useState(false);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        setLoading(true);
        const res = await incidentsApi.getIncidents({
          severity: selectedSeverity !== 'ALL' ? selectedSeverity : undefined,
          status: selectedStatus !== 'ALL' ? selectedStatus : undefined,
          limit: 50,
        });
        if (!cancelled) {
          setIncidents(res.incidents || []);
          if (selectedIncident) {
            const updated = (res.incidents || []).find(
              (i) => i.incident_id === selectedIncident.incident_id
            );
            if (updated) setSelectedIncident(updated);
          }
        }
      } catch {
        // Graceful fallback
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();
    return () => { cancelled = true; };
  }, [selectedSeverity, selectedStatus, selectedIncident, selectedIncident?.incident_id]);

  const fetchIncidents = async () => {
    try {
      setLoading(true);
      const res = await incidentsApi.getIncidents({
        severity: selectedSeverity !== 'ALL' ? selectedSeverity : undefined,
        status: selectedStatus !== 'ALL' ? selectedStatus : undefined,
        limit: 50,
      });
      setIncidents(res.incidents || []);
      if (selectedIncident) {
        const updated = (res.incidents || []).find(
          (i) => i.incident_id === selectedIncident.incident_id
        );
        if (updated) setSelectedIncident(updated);
      }
    } catch {
      // Graceful fallback
    } finally {
      setLoading(false);
    }
  };

  const handleSelectIncident = async (incident: Incident) => {
    try {
      const fullIncident = await incidentsApi.getIncident(incident.incident_id);
      setSelectedIncident(fullIncident);
    } catch {
      setSelectedIncident(incident);
    }
  };

  const handleStatusUpdate = async (incidentId: string, status: IncidentStatus) => {
    try {
      setUpdating(true);
      const updated = await incidentsApi.updateIncident(incidentId, { status });
      setSelectedIncident(updated);
      void fetchIncidents();
    } catch {
      // Ignore
    } finally {
      setUpdating(false);
    }
  };

  return (
    <div className="space-y-6">
      <PageHeader
        title="Security Incident Center"
        subtitle="Manage, investigate, and resolve security incidents generated by deterministic threat correlation rules (C-01 to C-05)."
        icon={AlertOctagon}
        badge="Incident Response"
        actions={
          <button
            onClick={() => { void fetchIncidents(); }}
            disabled={loading}
            className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold bg-white border border-slate-200 text-slate-700 hover:bg-slate-50 transition-colors shadow-xs"
          >
            <RefreshCw className={`w-3.5 h-3.5 ${loading ? 'animate-spin' : ''}`} />
            Refresh
          </button>
        }
      />

      {/* Filter Bar */}
      <div className="bg-white rounded-xl border border-slate-200 p-4 shadow-sm flex flex-wrap items-center justify-between gap-4">
        <div className="flex items-center gap-3 flex-wrap">
          <div className="flex items-center gap-2">
            <Filter className="w-4 h-4 text-slate-400" />
            <span className="text-xs font-semibold text-slate-600">Filters:</span>
          </div>

          <select
            value={selectedSeverity}
            onChange={(e) => setSelectedSeverity(e.target.value)}
            className="text-xs border border-slate-200 rounded-lg px-2.5 py-1.5 bg-slate-50 text-slate-700 font-medium focus:outline-none focus:ring-2 focus:ring-indigo-500/20"
          >
            <option value="ALL">All Severities</option>
            <option value="CRITICAL">Critical</option>
            <option value="HIGH">High</option>
            <option value="MEDIUM">Medium</option>
            <option value="LOW">Low</option>
          </select>

          <select
            value={selectedStatus}
            onChange={(e) => setSelectedStatus(e.target.value)}
            className="text-xs border border-slate-200 rounded-lg px-2.5 py-1.5 bg-slate-50 text-slate-700 font-medium focus:outline-none focus:ring-2 focus:ring-indigo-500/20"
          >
            <option value="ALL">All Statuses</option>
            <option value="OPEN">Open</option>
            <option value="INVESTIGATING">Investigating</option>
            <option value="RESOLVED">Resolved</option>
            <option value="FALSE_POSITIVE">False Positive</option>
          </select>
        </div>

        <div className="text-xs text-slate-500 font-medium">
          Showing <span className="font-bold text-slate-800">{incidents.length}</span> incident(s)
        </div>
      </div>

      {/* Main Grid: Incident List (1/2) + Incident Detail Panel (1/2) */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Incident List */}
        <div className="space-y-3">
          {incidents.length === 0 ? (
            <div className="bg-white rounded-xl border border-slate-200 p-12 text-center text-slate-400">
              <AlertOctagon className="w-8 h-8 mx-auto mb-2 opacity-40" />
              <p className="text-xs font-semibold text-slate-600">No Incidents Found</p>
              <p className="text-[11px] text-slate-400 mt-1">No security incidents match the current criteria.</p>
            </div>
          ) : (
            incidents.map((inc) => (
              <IncidentCard
                key={inc.id || inc.incident_id}
                incident={inc}
                isSelected={selectedIncident?.incident_id === inc.incident_id}
                onClick={() => handleSelectIncident(inc)}
                canManage={true}
                onStatusChange={(status) => handleStatusUpdate(inc.incident_id, status)}
              />
            ))
          )}
        </div>

        {/* Incident Detail Panel */}
        <div className="bg-white rounded-xl border border-slate-200 shadow-sm p-6">
          {selectedIncident ? (
            <div className="space-y-5">
              <div className="flex items-start justify-between gap-4 pb-4 border-b border-slate-100">
                <div>
                  <div className="flex items-center gap-2 mb-1.5">
                    <span className="font-mono text-xs font-bold text-slate-800 bg-slate-100 px-2 py-0.5 rounded">
                      {selectedIncident.incident_id}
                    </span>
                    <StatusBadge status={selectedIncident.severity} size="sm" />
                    <StatusBadge status={selectedIncident.status} size="sm" />
                  </div>
                  <h3 className="text-lg font-bold text-slate-900">{selectedIncident.title}</h3>
                </div>
              </div>

              {/* Status Action Buttons */}
              <div className="flex items-center gap-2 flex-wrap">
                <span className="text-xs font-semibold text-slate-500">Transition Status:</span>
                {['OPEN', 'INVESTIGATING', 'RESOLVED', 'FALSE_POSITIVE'].map((st) => (
                  <button
                    key={st}
                    disabled={updating || selectedIncident.status === st}
                    onClick={() => handleStatusUpdate(selectedIncident.incident_id, st as IncidentStatus)}
                    className={`text-xs px-2.5 py-1 rounded-lg font-semibold border transition-all ${
                      selectedIncident.status === st
                        ? 'bg-slate-100 text-slate-400 border-slate-200 cursor-not-allowed'
                        : 'bg-white text-slate-700 border-slate-200 hover:border-indigo-300 hover:bg-indigo-50/40'
                    }`}
                  >
                    {st}
                  </button>
                ))}
              </div>

              {/* Description */}
              <div className="space-y-1.5">
                <h4 className="text-xs font-bold uppercase tracking-wider text-slate-500">Description</h4>
                <p className="text-xs text-slate-700 bg-slate-50 p-3.5 rounded-lg border border-slate-100 leading-relaxed">
                  {selectedIncident.description}
                </p>
              </div>

              {/* Metadata Grid */}
              <div className="grid grid-cols-2 gap-3 text-xs">
                <div className="bg-slate-50 p-3 rounded-lg border border-slate-100">
                  <span className="text-slate-400 block mb-0.5">Correlated Events:</span>
                  <span className="font-mono font-bold text-slate-800">{selectedIncident.event_count}</span>
                </div>
                <div className="bg-slate-50 p-3 rounded-lg border border-slate-100">
                  <span className="text-slate-400 block mb-0.5">Source Session:</span>
                  {selectedIncident.source_session_id ? (
                    <Link
                      to={`/sessions/timeline?session_id=${selectedIncident.source_session_id}`}
                      className="font-mono font-semibold text-indigo-600 hover:underline truncate block"
                    >
                      {selectedIncident.source_session_id.slice(0, 16)}...
                    </Link>
                  ) : (
                    <span className="text-slate-400 font-mono">N/A</span>
                  )}
                </div>
                <div className="bg-slate-50 p-3 rounded-lg border border-slate-100">
                  <span className="text-slate-400 block mb-0.5">Created At:</span>
                  <span className="text-slate-700">{new Date(selectedIncident.created_at).toLocaleString()}</span>
                </div>
                <div className="bg-slate-50 p-3 rounded-lg border border-slate-100">
                  <span className="text-slate-400 block mb-0.5">Assigned Analyst:</span>
                  <span className="text-slate-700">{selectedIncident.assigned_to_user_id || 'Unassigned'}</span>
                </div>
              </div>

              {/* Correlated Events List */}
              {selectedIncident.correlated_events && selectedIncident.correlated_events.length > 0 && (
                <div className="space-y-2 pt-3 border-t border-slate-100">
                  <h4 className="text-xs font-bold uppercase tracking-wider text-slate-500">
                    Correlated Security Events ({selectedIncident.correlated_events.length})
                  </h4>
                  <div className="space-y-2 max-h-60 overflow-y-auto">
                    {selectedIncident.correlated_events.map((evt, idx) => (
                      <div key={evt.event_id || idx} className="bg-slate-50 p-2.5 rounded-lg border border-slate-100 text-xs">
                        <div className="flex items-center justify-between gap-2 mb-1">
                          <span className="font-mono font-semibold text-slate-800">{evt.event_type}</span>
                          <StatusBadge status={evt.severity} size="sm" />
                        </div>
                        <p className="text-slate-600 text-[11px]">{evt.message}</p>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          ) : (
            <div className="py-24 text-center text-slate-400">
              <Shield className="w-10 h-10 mx-auto mb-3 opacity-30 text-indigo-500" />
              <p className="text-sm font-semibold text-slate-600">Select an Incident</p>
              <p className="text-xs text-slate-400 mt-1">
                Choose an incident from the list to view correlated telemetry, events, and update triage status.
              </p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
